version: "3.7"
services:
  barikoi_maps:
    image: faiazhossain10@gmail.com/barikoi-maps:${TAG}
    container_name: barikoi-maps
    restart: unless-stopped
    env_file:
      - .env.local
    ports:
      - "4005:3000"
