/* eslint-disable @next/next/no-sync-scripts */
import Head from "next/head";
import { Inter } from "next/font/google";
// import MainMap from "@/components/MainMap/MainMap";

import dynamic from "next/dynamic";
const MainMap = dynamic(() => import("@/components/MainMap/MainMap"), {
  ssr: false,
});
const inter = Inter({ subsets: ["latin"] });
import Script from "next/script";

export default function Home() {
  return (
    <>
      <Head>
        <title>Barikoi Maps</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://unpkg.com/three@0.147.0/build/three.min.js"></script>
        <script src="https://unpkg.com/three@0.147.0/examples/js/loaders/GLTFLoader.js"></script>
      </Head>
      <main>
        <MainMap></MainMap>
      </main>
    </>
  );
}
